### PR TITLE
Update success copy when submitting a new project

### PR DESCRIPTION
**Pull request by gr-eg**

### CODE REVIEW

**Comment by Wardormeur** [comment]
I'd be tempted to make that parameterized on the event.requireApproval cc @conoramurphy @DanielBrierton

**Comment by DanielBrierton** [comment]
Again, would be nice for sure.

**Comment by Wardormeur** [comment]
See https://github.com/CoderDojo/coolest-platform/pull/62

**Comment by gr-eg** [comment]
How are you updating the USA branch from master, am I alright to cherry pick https://github.com/CoderDojo/coolest-platform/pull/67

**Comment by gr-eg** [comment]
I've mucked this PR up somehow! I'm just going to close it and start again....

**Pull request closed without merging**
