### PR TITLE
Replace the 3 logos with the new coolest project one

### LINKED ISSUE #104: Update logo
### Business Case
The platform is a global event, has a new unified brand that overtakes all previous brands. We need to use the latest branding.

### Task
Replace the current 3 logos with only the main Coolest Projects logo on both the platform and in the emails. https://coolestprojects.org/_nuxt/img/33df4a4.svg
Also update the favicon and anywhere else a logo is used.

### PR DESCRIPTION
**Pull request by damienh**
closes #104 

replace the previous 3 logos with the single coolest projects logo.

screen shot 2018-11-19 at 16 21 00
screen shot 2018-11-19 at 16 20 46

### CODE REVIEW

**Comment by Wardormeur** [comment]
Yep, so you might want to change https://github.com/CoderDojo/coolest-platform/blob/master/client/index.html#L19 as well :)

**Comment by damienh** [comment]
@Wardormeur what do I need to change there?

**Comment by damienh** [comment]
@Wardormeur ah do you mean add the others. Will do.

**Comment by damienh** [comment]
updated @conoramurphy @Wardormeur

**Pull request merged**
